name: Auto Deploy ðŸš€

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ðŸ“¤
        uses: actions/checkout@v3

      - name: Install dependencies ðŸ› ï¸
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add SSH host to known_hosts ðŸ”‘
        run: ssh-keyscan -p 8288 103.82.240.20 >> ~/.ssh/known_hosts

      - name: Deploy files via SCP ðŸ“¡
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -P 8288 -r . arunikaprawira@103.82.240.20:/var/www/vhosts/arunikaprawira.com/httpdocs/app.arunikaprawira.com/

      - name: âœ… Deployment Success
        run: echo "Deployment completed successfully!"
