name: Auto Deploy ğŸš€

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ“¤
        uses: actions/checkout@v3

      - name: Install sshpass ğŸ› ï¸
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy files via SCP ğŸ“¡
        run: |
          sshpass -p "ArunikaPrawira" scp -P 8288 -r . arunikaprawira@103.82.240.20:/home/arunikaprawira/httpdocs/app.arunikaprawira.com/

      - name: âœ… Deployment Success
        run: echo "Deployment completed successfully!"